baseurl      = "https://casvancooten.com"
title        = "Cas' Security Ramblings"
languageCode = "en-us"
theme        = "hello-friend-ng"
enableEmoji  = true
# PygmentsCodeFences = true
# PygmentsStyle = "native"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006"
  
  homeSubtitle = "I ramble about security stuff, mostly"

  disableReadOtherPosts = false

  description = "I ramble about security stuff, mostly"
  keywords = "homepage, blog, cas van cooten, security"

  images = ["/preview.png"]
  contentTypeName = "posts"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/chvancooten"

  [[params.social]]
    name = "email"
    url  = "mailto:hello@casvancooten.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/chvancooten"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/chvancooten/"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Cas van Cooten"
    subtitle = "I ramble about security stuff, mostly"
    keywords = "homepage, blog, cas van cooten, security, hacking"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Security Ramblings"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts/"
